#!/bin/sh
#
# forwarder.sh
# automatically generated by 'make rcscripts'. DO NOT edit
#
# environment variables starts here
BASEDIR="/var/dse"
VARDIR="/var/dse"
BINDIR="/var/dse/bin"
RCDIR="/var/dse/rc"
CFGDIR="/var/dse/cfg"
LOGDIR="/var/dse/log"
IFACE="ppp"
IFCFG="/var/dse/cfg/iface.cfg"
IFINFOFILE="/var/dse/cfg/ifinfo.cfg"
RUNUSR="forward"
USRCFG="/var/dse/cfg/user.cfg"
NETWORK="150.1.93.0"
MASK="16"
SUBNET="150.1.93.0/16"
BINDADDR="150.1.255.255"
BINDPORT="6000"
PEERPORT="7860"
CONFIG_H="config.h"
PORTS="6000"
PORTSCFG="/var/dse/cfg/ports.cfg"
EXENAME="forwarder"
EXEPATH="/var/dse/bin/forwarder"
EXECFG="/var/dse/cfg/exe.cfg"
INITSCRIPT="/etc/init.d/forwarder"
EXT=".sh"
FORWARDER_RC="forwarder.sh"
UPDIFLIST_RC="update-iflist.sh"
IPUP_RC="ip-up.sh"
IPDOWN_RC="ip-down.sh"
LOCAL_RC="local.sh"
FIREWALL_RC="firewall.sh"
BINFILES="forwarder"
RCFILES="forwarder.sh update-iflist.sh ip-up.sh ip-down.sh local.sh firewall.sh"
TARGETS="forwarder sender receiver forwarder.debug"
OTHERS="config.h"
ENVFILE="env.source"
LOCKFILE="/var/lock/subsys/forwarder"
# environment variables ends here

# function definition starts here
function start() {
  PID=`/sbin/pidof $EXEPATH`
  if [ "$PID" != "" ] ; then
    echo "$EXENAME already running. Try stopping first"
    return 1
  fi
  echo "Starting $EXENAME ..."
  for port in `cat $PORTSCFG` ; do
    echo "+++Listening on $BINDADDR:$port"
    $EXEPATH $BINDADDR $port &> "${LOGDIR}/log.${EXENAME}.${port}"&
  done
  RETVAL=$?
  touch $LOCKFILE &> /dev/null
  return $RETVAL
}

function update() {
  echo -n "Updating interface list [sending HUP to $EXENAME] ..."
  PID=`/sbin/pidof $EXEPATH`
  if [ "$PID" = "" ] ; then
    echo "$EXENAME is not running"
    return 1
  fi
  kill -HUP $PID
  return $?
}

function stop() {
  echo -n "Stopping $EXENAME ..."
  PID=`/sbin/pidof $EXEPATH`
  if [ "$PID" = "" ] ; then
    echo "$EXENAME not running..."
    return 0
  fi
#  echo "Killing [$PID] ..."
  kill -INT $PID
  RETVAL=$?
  if [ -f $LOCKFILE ] ; then
    rm -f $LOCKFILE &> /dev/null
  fi
  return $RETVAL
}

function restart() {
  eval stop
  eval start
  return $?
}

function status() {
  echo "Status ..."
  PID=`/sbin/pidof $EXEPATH`
  if [ "$PID" = "" ] ; then
    echo "$EXENAME is not running"
  else
    echo "$EXENAME is running... pid=[$PID]"
    ps up $PID
  fi
  return $?
}

function iflist() {
  echo "List of interfaces to forward packets to"
  if [ -f $IFINFOFILE ] ; then
    cat $IFINFOFILE
  fi
  return $?
}

if [ $# -lt 1 ] ; then
  echo "Usage: $0 {start|stop|update|restart|status|iflist}"
  exit 1
fi

eval $1

if [ $? -eq 0 ] ; then
  echo "[  OK  ]"
else
  echo "[FAILED]"
fi
