#!/bin/sh
#
# ip-down.sh
# automatically generated by 'make rcscripts'. DO NOT edit
#
# environment variables starts here
BASEDIR="/var/dse"
VARDIR="/var/dse"
BINDIR="/var/dse/bin"
RCDIR="/var/dse/rc"
CFGDIR="/var/dse/cfg"
LOGDIR="/var/dse/log"
IFACE="ppp"
IFCFG="/var/dse/cfg/iface.cfg"
IFINFOFILE="/var/dse/cfg/ifinfo.cfg"
RUNUSR="forward"
USRCFG="/var/dse/cfg/user.cfg"
NETWORK="150.1.93.0"
MASK="16"
SUBNET="150.1.93.0/16"
BINDADDR="150.1.255.255"
BINDPORT="6000"
PEERPORT="7860"
CONFIG_H="config.h"
PORTS="6000"
PORTSCFG="/var/dse/cfg/ports.cfg"
EXENAME="forwarder"
EXEPATH="/var/dse/bin/forwarder"
EXECFG="/var/dse/cfg/exe.cfg"
INITSCRIPT="/etc/init.d/forwarder"
EXT=".sh"
FORWARDER_RC="forwarder.sh"
UPDIFLIST_RC="update-iflist.sh"
IPUP_RC="ip-up.sh"
IPDOWN_RC="ip-down.sh"
LOCAL_RC="local.sh"
FIREWALL_RC="firewall.sh"
BINFILES="forwarder"
RCFILES="forwarder.sh update-iflist.sh ip-up.sh ip-down.sh local.sh firewall.sh"
TARGETS="forwarder sender receiver forwarder.debug"
OTHERS="config.h"
ENVFILE="env.source"
LOCKFILE="/var/lock/subsys/forwarder"
# environment variables ends here


$RCDIR/$UPDIFLIST_RC
chmod 644 $IFINFOFILE
$RCDIR/$FORWARDER_RC update
echo "Logged out at  `date`" >> $LOGDIR/login.log
